export type RootStackParamList = {
  MainTabs: undefined;
  Onboarding: undefined;
  Login: undefined;
  TroubleLogin: undefined;
  OTP: { isLogin?: boolean; phoneNumber?: string } | undefined;
  ForgotPassword: undefined;
  TwoStepVerificationIssue: undefined;
  TotpLogin: { preAuthToken: string };
  ChangePhoneNumber: undefined;
  AccountDeactivated: undefined;
  NewDeviceLogin: undefined;
  ResetPassword: undefined;
  ResetOTP: undefined;
  SignUpNumber: undefined;
  SignUpEmail: undefined;
  SignUpPassword: undefined;
  SignUpName: undefined;
  SignUpAddress: undefined;
  SignUpPronouns: undefined;
  SignUpEmployment: undefined;
  SignUpBirthday: undefined;
  TaxResidency: undefined;
  CreatePasscode: undefined;
  ConfirmPasscode: { firstPasscode: string };
  Consent: undefined;
  FeesAndLimits: undefined;
  VerifyIdentity: { isPEP?: boolean };
  SourceofFund: { isPEP?: boolean };
  Idtype: { isPEP?: boolean };
  VerifyFaceId: { isPEP?: boolean };
  ScanId: { isPEP?: boolean };
  ScanIdBack: { isPEP?: boolean };
  SelfieScan: { isPEP?: boolean };
  PEPStatus: undefined;
  PEPDetails: undefined;
  PEPAccountPurpose: undefined;
  PEPProofOfWealth: undefined;
  PEPUnderReview: undefined;
  KYCSuccess: undefined;
  CreatingAccount: undefined;
  AccountReady: undefined;
  Reason: undefined;
  Refund: undefined;
  Statement: undefined;
  TalkToUs: undefined;
  EmailUs: undefined;
  ChatWithUs: undefined;
  EnableNotification: undefined;
  EnableBiometrics: undefined;
  Send: undefined;
  Profile: undefined;
  Appearance: undefined;
  Receive: undefined;
  HelpAndSupport: undefined;
  Inbox: undefined;
  NotificationSettings: undefined;
  SendAmount: { name: string; username: string; avatar: string };
  SendConfirm: { name: string; username: string; avatar: string; amount: number; note: string };
  SendPin: { name: string; username: string; avatar: string; amount: number; note: string };
  SendSuccess: { name: string; username: string; avatar: string; amount: number; note: string };
  RequestAmount: { name: string; username: string; avatar: string };
  SecurityAndPrivacy: undefined;
  ChangePassword: undefined;
  SecureAccount: undefined;
  LogoutEverywhere: undefined;
  Devices: undefined;
  TwoStepVerification: undefined;
  FindMeBy: undefined;
  BillForwardingIntro: undefined;
  BillForwardingDetails: undefined;
  PersonalDetails: undefined;
  PersonalInformation: undefined;
  ChangeEmail: undefined;
  ChangePhone: undefined;
  ChatScreen: { id: string; name: string; avatar: string; online: boolean; sentMedia?: any[] | undefined; forwardedMessage?: any };
  Hub: undefined;
  MiniApp: { appId: string };
  ContactsProfile: { name: string; username: string; avatar: string; phone?: string; status?: string; accountProvider?: string };
  ChatCamera: { recipientName: string; chatId: string };
  MediaPreview: {
    media: Array<{ uri: string; type: 'image' | 'video' }>;
    recipientName: string;
    chatId: string;
    source: 'gallery' | 'camera';
  };
  Details: undefined;
  Spending: undefined;
  Withdraw: undefined;
  StatementDownload: undefined;
  Transactions: { balance: string };
  ChatInfoScreen: { name: string; username: string; avatar: string; phone?: string; status?: string; accountProvider?: string; mediaCount?: number; storageStats?: any };
  AudioCall: { name: string; avatar: string };
  VideoCall: { name: string; avatar: string };
  StarredMessages: undefined;
  SharedMedia: undefined;
  ManageStorage: { storageStats?: any } | undefined;
  MessageInfo: { message: any };
};
