export type RootStackParamList = {
  MainTabs: undefined;
  Onboarding: undefined;
  Login: undefined;
  TroubleLogin: undefined;
  OTP: undefined;
  ForgotPassword: undefined;
  TwoStepVerificationIssue: undefined;
  ChangePhoneNumber: undefined;
  AccountDeactivated: undefined;
  NewDeviceLogin: undefined;
  ResetPassword: undefined;
  ResetOTP: undefined;
  SignUpNumber: undefined;
  SignUpEmail: undefined;
  SignUpPassword: undefined;
  SignUpName: undefined;
  SignUpAddress: undefined;
  SignUpPronouns: undefined;
  SignUpEmployment: undefined;
  SignUpBirthday: undefined;
  TaxResidency: undefined;
  CreatePasscode: undefined;
  ConfirmPasscode: { firstPasscode: string };
  Consent: undefined;
  FeesAndLimits: undefined;
  VerifyIdentity: { isPEP?: boolean };
  SourceofFund: { isPEP?: boolean };
  Idtype: { isPEP?: boolean };
  VerifyFaceId: { isPEP?: boolean };
  ScanId: { isPEP?: boolean };
  ScanIdBack: { isPEP?: boolean };
  SelfieScan: { isPEP?: boolean };
  PEPStatus: undefined;
  PEPDetails: undefined;
  PEPAccountPurpose: undefined;
  PEPProofOfWealth: undefined;
  PEPUnderReview: undefined;
  KYCSuccess: undefined;
  CreatingAccount: undefined;
  AccountReady: undefined;
  Reason: undefined;
  Refund: undefined;
  Statement: undefined;
  TalkToUs: undefined;
  EmailUs: undefined;
  ChatWithUs: undefined;
  EnableNotification: undefined;
  EnableBiometrics: undefined;
};
