import type { StorageDetails, Message as ChatMessage } from '../components/chat/chatTypes';

export type RootStackParamList = {
  MainTabs: undefined;
  Onboarding: undefined;
  Login: undefined;
  TroubleLogin: undefined;
  ForgotPassword: undefined;
  TwoStepVerificationIssue: undefined;
  TotpLogin: { preAuthToken?: string; loginIdentifier?: string; methods?: string[]; defaultMethod?: string };
  RecoveryCodeLogin: { preAuthToken: string };
  AppLoginApproval: { requestId: string; deviceName: string; ipAddress: string };
  ChangePhoneNumber: undefined;
  AccountDeactivated: undefined;
  NewDeviceLogin: undefined;
  ResetPassword: undefined;
  ResetOTP: { email: string };
  ResetNewPassword: { email: string; code: string };
  SignUpNumber: undefined;
  SignUpEmail: undefined;
  SignUpPassword: undefined;
  SignUpName: undefined;
  SignUpHandle: undefined;
  SignUpAddress: undefined;
  SignUpPronouns: undefined;
  SignUpEmployment: undefined;
  SignUpBirthday: undefined;
  TaxResidency: undefined;
  CreatePasscode: undefined;
  ConfirmPasscode: { firstPasscode: string };
  Consent: undefined;
  TermsOfService: undefined;
  PrivacyPolicy: undefined;
  FeesAndLimits: undefined;
  VerifyIdentity: { isPEP?: boolean };
  SourceofFund: { isPEP?: boolean };
  Idtype: { isPEP?: boolean };
  VerifyFaceId: { isPEP?: boolean };
  ScanId: { isPEP?: boolean };
  ScanIdBack: { isPEP?: boolean };
  SelfieScan: { isPEP?: boolean };
  PEPStatus: undefined;
  PEPDetails: undefined;
  PEPAccountPurpose: undefined;
  PEPProofOfWealth: undefined;
  PEPUnderReview: undefined;
  KYCRejected: undefined;
  KYCSuccess: undefined;
  CreatingAccount: undefined;
  AccountReady: undefined;
  Reason: undefined;
  Refund: undefined;
  Statement: undefined;
  TalkToUs: undefined;
  EmailUs: undefined;
  ChatWithUs: undefined;
  ChatbotScreen: undefined;
  EnableNotification: undefined;
  EnableBiometrics: undefined;
  Send: undefined;
  Profile: undefined;
  LimitsAndUsage: undefined;
  LimitIncreaseRequest: undefined;
  Appearance: undefined;
  Receive: undefined;
  HelpAndSupport: undefined;
  HelpTopic: { topicId: string; title: string };
  Inbox: undefined;
  NotificationSettings: undefined;
  SendAmount: { id?: string; name?: string; username?: string; avatar?: string; identifier: string; amount?: number; note?: string; merchantVerified?: boolean };
  SendConfirm: { name: string; username: string; avatar: string; amount: number; note: string; identifier: string; category?: string };
  SendPin: { name: string; username?: string; avatar?: string; amount: number; note: string; identifier: string; id?: string; category?: string };
  SendSuccess: { name: string; username?: string; avatar?: string; amount: number; note: string; identifier: string; category?: string; transactionId?: string };
  RequestAmount: { id?: string; name: string; username: string; avatar: string; identifier: string };
  SecurityAndPrivacy: undefined;
  ChangePassword: undefined;
  SecureAccount: undefined;
  LogoutEverywhere: undefined;
  Devices: undefined;
  TwoStepVerification: undefined;
  AppSecurity: { disableAppLock?: boolean } | undefined;
  TotpSetup: undefined;
  DisableTotp: undefined;
  RecoveryCodes: { codes: string[] };
  ManageRecoveryCodes: undefined;
  AccountRecoveryContacts: undefined;
  GenerateRecoveryCode: { requestId: string; requesterName: string; requesterHandle?: string };
  ContactRecoveryLogin: { preAuthToken: string };
  SmsSetup: undefined;
  DisableSms: undefined;
  PasskeySetup: undefined;
  DisablePasskey: undefined;
  AzaAppSetup: undefined;
  FindMeBy: undefined;
  BillForwardingIntro: undefined;
  BillForwardingDetails: undefined;
  PersonalDetails: undefined;
  PersonalInformation: undefined;
  VerifyPasscode: { onSuccessScreen: keyof RootStackParamList; onSuccessParams?: Record<string, unknown> };
  ChangeEmail: undefined;
  ChangePhone: undefined;
  ChatScreen: { id: string; name: string; avatar: string; online: boolean; payIdentifier?: string; sentMedia?: Array<{ uri: string; type: 'image' | 'video' }> | undefined; forwardedMessage?: ChatMessage; quickReply?: string };
  Hub: undefined;
  MiniApp: { appId: string };
  ContactsProfile: { id?: string; name: string; username: string; avatar: string; phone?: string; status?: string; accountProvider?: string };
  ChatCamera: { recipientName: string; chatId: string };
  MediaPreview: {
    media: Array<{ uri: string; type: 'image' | 'video' }>;
    recipientName: string;
    chatId: string;
    source: 'gallery' | 'camera';
  };
  Details: undefined;
  Spending: undefined;
  Withdraw: undefined;
  StatementDownload: undefined;
  Transactions: { balance: string };
  ReversalRequest: undefined;
  AddFriends: undefined;
  RequestPending: undefined;
  ChatInfoScreen: { id?: string; name: string; username: string; avatar: string; phone?: string; status?: string; accountProvider?: string; mediaCount?: number; storageStats?: StorageDetails };
  ChatThemeScreen: { chatId: string; name: string };
  AudioCall: { callId?: string; name: string; avatar: string };
  VideoCall: { callId?: string; name: string; avatar: string };
  IncomingCall: undefined;
  StarredMessages: undefined;
  SharedMedia: { chatId?: string | undefined; otherUserName?: string | undefined } | undefined;
  ManageStorage: { storageStats?: StorageDetails } | undefined;
  ChatBackup: undefined;
  MessageInfo: { message: ChatMessage };
  DeleteAccount: undefined;
  MerchantBusinessName: undefined;
  MerchantBusinessCategory: { businessName: string; businessHandle: string };
  MerchantBusinessContact: { businessName: string; businessHandle: string; category: string };
  MerchantKYBIntro: { merchantId: string };
  MerchantKYBBusiness: { merchantId: string };
  MerchantKYBOwner: { merchantId: string; businessType: string; registrationNumber?: string; registeredAddress?: string; city?: string; taxIdNumber?: string; website?: string };
  MerchantKYBDocuments: { merchantId: string; isPrimaryOwner: boolean };
  MerchantKYBSubmitted: undefined;
  RecurringTransfers: undefined;
  CreateRecurringTransfer: undefined;
  BulkTransfer: undefined;
  SpendingCategories: undefined;
  WalletFreeze: undefined;
  FinancialDashboard: undefined;
  BudgetManagement: undefined;
  AiAssistant: undefined;
  QrLoginApproval: { challengeToken: string; siteType: string; siteName: string; oauthClientId?: string; oauthScopes?: string };
  GeoBlocked: undefined;
  ConnectedApps: undefined;
  MerchantCheckout: { sessionId: string };
  StatementVerifyResult: { code: string };
  MerchantVerifyResult: { handle: string; amount?: number; note?: string };
  PaymentVerifyResult: { ref: string; sig: string };
  PaymentProof: { transactionId: string };
  OAuthPaymentApproval: { sessionId: string };
  BroadcastScreen: { preselected?: string[] };
  SavedMessagesScreen: undefined;
};
