export { default as VerifyIdentityScreen } from './VerifyIdentityScreen';
export { default as SourceofFundsScreen} from './SourceofFundsScreen';
export { default as IdtypeScreen } from './IdtypeScreen';
export { default as VerifyFaceIdScreen } from './VerifyFaceIdScreen';
export { default as ScanIdScreen } from './ScanIdScreen';
export { default as ScanIdBackScreen } from './ScanIdBackScreen';
export { default as SelfieScanScreen } from './SelfieScanScreen';
export { default as PEPStatusScreen } from './PEPStatusScreen';
export { default as PEPDetailsScreen } from './PEPDetailsScreen';
export { default as PEPAccountPurposeScreen } from './PEPAccountPurposeScreen';
export { default as PEPProofOfWealthScreen } from './PEPProofOfWealthScreen';
export { default as PEPUnderReviewScreen } from './PEPUnderReviewScreen';
export { default as KYCSuccessScreen } from './KYCSuccessScreen';
