export { default as VerifyIdentityScreen } from './screens/VerifyIdentityScreen';
export { default as IdtypeScreen } from './screens/IdtypeScreen';
export { default as ScanIdScreen } from './screens/ScanIdScreen';
export { default as ScanIdBackScreen } from './screens/ScanIdBackScreen';
export { default as VerifyFaceIdScreen } from './screens/VerifyFaceIdScreen';
export { default as SelfieScanScreen } from './screens/SelfieScanScreen';
export { default as SourceofFundsScreen } from './screens/SourceofFundsScreen';
export { default as KYCSuccessScreen } from './screens/KYCSuccessScreen';
export { default as KYCRejectedScreen } from './screens/KYCRejectedScreen';
export * from './pep';
