spring.application.name=backend
 #server
server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/aza_db
spring.datasource.username=aza_user
spring.datasource.password=aza_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT (we'll use these later)
app.jwt.secret=my-super-secret-key-change-this-in-production-make-it-long
app.jwt.access-expiration-ms=900000
app.jwt.refresh-expiration-ms=2592000000